{% set name = "fsleyes" %}
{% set version = "1.20.1" %}
{% set python_min = "3.11" %}
{% set sha256 = "4097ea7bc82fe7c3df6dfbe3f213ea0503d00be5aaa068d3c0297ade68c5695c" %}

package:
  name: {{ name }}
  version: {{ version }}


source:
  url: https://pypi.org/packages/source/f/fsleyes/fsleyes-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:

    # Set GDK_BACKEND=x11, as the conda-forge
    # wxwidgets package is built to use GLX
    # and not EGL for OpenGL interaction
    #
    # Add $PREFFIX/share/ to XDG_DATA_DIRS,
    # as this may not otherwise be found if
    # if XDG_DATA_DIRS is set on the host
    # platform.
    - envvars.patch

    # Disable/suppress logging, and disable
    # OpenGL error checking
    - logging.patch

    # Make sure the OpenGL libs can be found
    # on macOS, and allow execution of GUI
    # aps from non-framework python
    # installations.
    - opengl.patch

build:
  number: 1
  noarch: python
  osx_is_app: true
  entry_points:
    - render             = fsleyes.render:main
    - fsleyes_unfiltered = fsleyes.main:main
    - fsleyes            = fsleyes.filtermain:main


requirements:
  build:
    - sphinx >=1.7
    - sphinx_rtd_theme
    - mock
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - __{{ noarch_platform }}
    - python >={{ python_min }}
    {% if noarch_platform == "osx" %}
    - tk !=8.6.9
    - appnope ==0.1.*
    {% endif %}
    - dcm2niix >=1.0.20181114
    - file-tree
    - file-tree-fsl
    - fsleyes-props >=1.13
    - fsleyes-widgets >=0.17
    - fslpy >=3.22
    - indexed_gzip >=0.7
    - ipykernel >=4.8
    - ipython >=5
    - jinja2 >=2
    - jupyter_client >=5.3.1
    - matplotlib-base >=3.5
    - nbclassic
    - nibabel >=2.3
    - numpy >=1.14
    - pillow >=3.2.0
    - pyopengl >=3.1.0
    - pyparsing >=3
    - pyzmq >=17
    - rtree >=0.8.3
    - scipy >=0.18
    - tornado >=5
    - trimesh >=2.37.29
    - trx-python >=0.4.0
    - wxnatpy >=0.4.0
    - wxpython >=4
    - xnat >=0.3.3

test:

  requires:
    - python {{ python_min }}
    # need osmesa on linux
    {% if noarch_platform == "linux" %}
    - mesalib 25.0.*
    {% endif %}

  imports:
    - fsleyes
    - fsleyes.actions
    - fsleyes.controls
    - fsleyes.displaycontext
    - fsleyes.editor
    - fsleyes.gl
    - fsleyes.plotting
    - fsleyes.plugins
    - fsleyes.profiles
    - fsleyes.views
  source_files:
    - fsleyes/assets/icons/app_icon.png
  commands:
    - fsleyes -V
    - fsleyes -h
    # The conda-forge CI Windows
    # env does not have OpenGL
    {% if noarch_platform != "win" %}
    - fsleyes render -of out.png fsleyes/assets/icons/app_icon.png
    {% endif %}

app:
  entry: fsleyes
  summary: The FSL image viewer
  type: desk
  icon: logo.png

about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsleyes/fsleyes/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The FSL image viewer
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fsleyes/fsleyes/

extra:
  recipe-maintainers:
    - pauldmccarthy
